# Database - Neon
spring.datasource.url=jdbc:postgresql://ep-dawn-sea-antjpztw-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_MrJdBW2x9Zuf
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt-secret=mySecretKeyForJWTTokenGenerationThatIsLongEnough123456
app.jwt-expiration=86400000
app.jwt-expiration-milliseconds=86400000