# Local Development Configuration
spring.datasource.url=jdbc:postgresql://ep-dawn-sea-antjpztw-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_MrJdBW2x9Zuf
app.jwt-secret=a-very-long-secure-random-jwt-secret-key-that-must-be-at-least-256-bits
app.jwt-expiration-milliseconds=86400000
