# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-dawn-sea-antjpztw-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_MrJdBW2x9Zuf}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt-secret=${JWT_SECRET:mySecretKeyForJWTTokenGenerationThatIsLongEnough123456}
app.jwt-expiration=86400000
app.jwt-expiration-milliseconds=86400000